project:
  type: website
  resources:
    - CNAME

website:
  title: "#rstats.fyi"
  site-url: https://rstats.fyi
  repo-url: https://github.com/jonthegeek/rstats.fyi
  repo-actions: [source, issue]
  # google-analytics: "G-QQ1ZV766J5"
  # cookie-consent: true
  navbar:
    # background: "#445D48"
    # logo: images/r4ds-logo-150px.png
    # logo-alt: "R4DS Online Learning Community"
    # title: false
    tools:
      - icon: mastodon
        href: https://fosstodon.org/@rstatsfyi
      - icon: linkedin
        href: https://www.linkedin.com/in/jonthegeek/
      - icon: github
        href: https://github.com/jonthegeek/
    left:
      # - href: training.qmd
      #   text: Training
      # - href: about.qmd
      #   text: About
      - href: pd2023.qmd
        text: Professional Development
      # - href: contact.qmd
      #   text: Contact
  page-footer:
    center:
      - text: "© 2023 Jon Harmon"
        href: https://rstats.fyi

format:
  html:
    theme:
      dark: [flatly, theme.scss]
      light: [darkly, theme.scss]
    css: styles.css
    toc: false
    link-external-newwindow: true
